category_codes = {
    '1': 'Film & Animation',
    '2': 'Autos & Vehicles',
    '10': 'Music',
    '15': 'Pets & Animals',
    '17': 'Sports',
    '20': 'Gaming',
    '22': 'People & Blogs',
    '23': 'Comedy',
    '24': 'Entertainment',
    '25': 'News & Politics',
    '26': 'Howto & Style',
    '27': 'Education',
    '28': 'Science & Technology',
    '29': 'Nonprofits & Activism'
}


youtube_language_codes = {
    "en": "English",
    "hi": "Hindi",
    "es": "Spanish",
    "fr": "French",
    "de": "German",
    "ru": "Russian",
    "ja": "Japanese",
    "ko": "Korean",
    "pt": "Portuguese",
    "ar": "Arabic",
    "tr": "Turkish",
    "zh": "Chinese (Simplified)",
    "zh-Hant": "Chinese (Traditional)",
    "bn": "Bengali",
    "te": "Telugu",
    "ta": "Tamil",
    "mr": "Marathi",
    "ur": "Urdu",
    "it": "Italian",
    "id": "Indonesian",
    "th": "Thai",
    "vi": "Vietnamese",
    "ms": "Malay",
    "pl": "Polish",
    "nl": "Dutch",
    "fa": "Persian",
    "en-US": "English (United States)",
    "en-GB": "English (United Kingdom)",
    "en-IN": "English (India)",
    "ml": "Malayalam",
    "gu": "Gujarati",
    "kn": "Kannada",
    "pa": "Punjabi",
    "or": "Odia",
    "bh": "Bhojpuri",
    "zxx": "No linguistic content",
    "hi-Latn": "Hindi (Latin script)",
    "unknown": "Unknown"
}


